security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [CommongroundApplicationProvider, CommongroundDigispoofProvider, CommongroundEherkenningProvider, CommongroundUserProvider]
        commongroundApplicationProvider:
            id: Conduction\CommonGroundBundle\Security\User\CommongroundApplicationProvider
        commongroundUserProvider:
            id: Conduction\CommonGroundBundle\Security\User\CommongroundUserProvider
        commongroundDigispoofProvider:
            id: Conduction\CommonGroundBundle\Security\User\CommongroundDigispoofProvider
        commongroundEherkenningProvider:
            id: Conduction\CommonGroundBundle\Security\User\CommongroundEherkenningProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|docs)/
            security: false
        # The mollie webhook does not have our API key
        webhook:
            anonymous: true
            pattern: ^/payments/mollie_webhook
            methods: [POST]
        digispoof:
            anonymous: ~
            pattern: ^/digispoof
            form_login:
                login_path: app_user_digispoof
                check_path: app_user_digispoof
            logout:
                path: app_user_logout2
                target: app_user_digispoof
            stateless: false
            provider: commongroundDigispoofProvider
            guard:
                authenticators:
                    - Conduction\CommonGroundBundle\Security\CommongroundApplicationAuthenticator
                    - Conduction\CommonGroundBundle\Security\CommongroundUserAuthenticator
                    - Conduction\CommonGroundBundle\Security\CommongroundDigispoofAuthenticator
                entry_point: Conduction\CommonGroundBundle\Security\CommongroundApplicationAuthenticator
        eherkenning:
            anonymous: ~
            pattern: ^/eherkenning
            form_login:
                login_path: app_user_eherkenning
                check_path: app_user_eherkenning
            logout:
                path: app_user_logout2
                target: app_user_eherkenning
            stateless: false
            provider: commongroundEherkenningProvider
            guard:
                authenticators:
                    - Conduction\CommonGroundBundle\Security\CommongroundApplicationAuthenticator
                    - Conduction\CommonGroundBundle\Security\CommongroundUserAuthenticator
                    - Conduction\CommonGroundBundle\Security\CommongroundDigispoofAuthenticator
                    - Conduction\CommonGroundBundle\Security\CommongroundEherkenningAuthenticator
                entry_point: Conduction\CommonGroundBundle\Security\CommongroundApplicationAuthenticator
        main:
            anonymous: ~
            form_login:
                login_path: app_user_login
                check_path: app_user_login
            logout:
                path: app_user_logout2
                target: app_user_login
            stateless: false
            provider: commongroundUserProvider
            guard:
                authenticators:
                    - Conduction\CommonGroundBundle\Security\CommongroundApplicationAuthenticator
                    - Conduction\CommonGroundBundle\Security\CommongroundUserAuthenticator
                    - Conduction\CommonGroundBundle\Security\CommongroundDigispoofAuthenticator
                entry_point: Conduction\CommonGroundBundle\Security\CommongroundApplicationAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
