apiVersion: v1
appVersion: V.0.1
description: 'Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.'
name: pan
version: 0.1.0
home: www.zuid-drecht.nl
icon: www.zuid-drecht.nl